


all:
	../../../../../firefox -chrome chrome://agrisig/content/gestseax/source/gestsea.xul

c:
	../../../../../firefox -chrome chrome://agrisig/content/gestseax/gestsea/gestsea_cotisation.xul

d:
	../../../../../firefox chrome://agrisig/content/gestseax/gestsea/gestsea_cotisation.xul


bbb:
	../../../../../firefox -chrome chrome://agrisig/content/gestseax/gestsea/gestsea_builder.xul

ggg:
	../../../../../firefox -chrome chrome://agrisig/content/gestseax/gestsea/gestsea_general.xul

x:
	../../../../../firefox -chrome chrome://agrisig/content/gestseax/gestsea/gestseax.xul

clean:
	rm -f *~ generateur/*~ source/*~ gestsea/*~

