


all:
	../../../../../firefox -chrome chrome://agrisig/content/agrisig/src/agrisig.xul

x:
	../../../../../firefox -chrome chrome://agrisig/content/agrisig/bin/agrisig.xul

clean:
	rm *~ lib/*~ src/*~ bin/*~

